name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_ignored: html,css,g-code,batchfile
          plugin_languages_sections: recently-used          
          plugin_projects: yes
          plugin_projects_repositories: landaumedia/infrastructure/projects/39
          plugin_projects_limit: 0
          plugin_projects_descriptions: yes        
